# Generated by Django 4.2.1 on 2023-05-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
