# Generated by Django 4.2.1 on 2023-05-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userbookrelation_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelation',
            old_name='comment',
            new_name='commented',
        ),
    ]
