# Generated by Django 4.2.1 on 2023-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_comment_userbookrelation_commented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='commented',
            field=models.CharField(max_length=70),
        ),
    ]
