# Generated by Django 4.2.1 on 2023-05-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_userbookrelation_commented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookrelation',
            old_name='commented',
            new_name='comment',
        ),
    ]
