# Generated by Django 4.2.1 on 2023-05-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookrelation',
            name='comment',
        ),
    ]
